services:
  mysql_db:
    container_name: mysql_db
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: monAnnuaire
      MYSQL_USER: lilian
      MYSQL_PASSWORD: mysecret
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - ./script/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 10s

  spring_app:
    container_name: gestionCompteAPP
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/monAnnuaire?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: lilian
      SPRING_DATASOURCE_PASSWORD: mysecret
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    ports:
      - "8081:8080"
    networks:
      - mynetwork

  # Service phpMyAdmin
  phpmyadmin:
    # Version de l'image phpmyadmin
    image: phpmyadmin:5.2
    # Permet que le conteneur se redémarre tout le temps s'il est dans l'état stop
    restart: always
    # Permet que le service de backup démarre après la bd
    depends_on:
      mysql_db:
        condition: service_healthy
    # Variables d'environnement recupéré par secret
    environment:
      PMA_HOST: mysql_db
      MYSQL_USER: lilian  # ← Ajout
      MYSQL_PASSWORD: mysecret
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8090:80"
    # Réseaux sur lequel sont connectés les base de données mysql
    networks:
      - mynetwork

volumes:
  mysql_data:
    driver: local

networks:
  mynetwork:
