services:
  # Service MySQL
  db:
    image: mysql:latest
    restart: always
    container_name: mysql_db
    env_file:
      - "configmap.env"
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_db_password
    secrets:
      - mysql_db_password
      - mysql_db_root_password
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - database
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Application Spring Boot v1
  spring-appv1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_v1
    ports:
      - "8081:8080"
    depends_on:
      - db
    env_file:
      - "configmap.env"
    environment:
      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/mysql_db_password
    secrets:
      - mysql_db_password
    networks:
      - database

  # Service phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    env_file:
      - "configmap.env"
    environment:
      PMA_PASSWORD_FILE: /run/secrets/mysql_db_password
    secrets:
      - mysql_db_password
    ports:
      - "8083:80"
    depends_on:
      - db
    networks:
      - database

networks:
  database:
    driver: bridge
  frontend:
    driver: bridge
  backend:
    driver: bridge
